// <auto-generated />
namespace CollectTrash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resetcustomerandemployeetables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetcustomerandemployeetables));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311956298_reset customer and employee tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
